### ISSUE TITLE
使用过程中,报错 类加载不到

### ISSUE THREAD

**Issue by dlkhsro** [Jimmy-Shi/bean-query#12]
![image](https://user-images.githubusercontent.com/25053237/30200728-b186ce3a-94aa-11e7-9a45-51c65c8ffd83.png)
` temp = select(PayMessageBean.class)
                .where(
                        allOf(value("payDateTime", greaterThan(start)), value("payDateTime", lessThan(end)))
                ).executeFrom(pmbs);
`
payDateTime是毫秒数,,,,筛选在start和end之间的数据.

**Comment by Jimmy-Shi** [comment]
看起来是你的开发环境中缺乏一个java.beans.PropertyDescriptor的类
